### ISSUE TITLE
Error 1062: Duplicate entry '48965e50-af1b-5766-9d0d-22e42d0327dc' for key 'PRIMARY'

### ISSUE THREAD

**Issue by Mountains-and-rivers** [TalLannder/beego-ureg#3]
i got an error when i post my signup form.

34:05.1547321 +0800 CST }2019/06/15 19:34:05 [signup.go:100][E] SignupController:Post - Got err inserting user to the database:  Error 1062: Duplicate entry '48965e50-af1b-5766-9d0d-22e42d0327dc' for key 'PRIMARY'

why?can you help me?

**Comment by OnlyLoveOleg** [comment]
@Mountains-and-rivers Hey there! Sorry for the late reply. Not sure how much I can help since my schedule is pretty busy at the moment. For some reason the error indicates that the application is trying to create a record in the DB with primary key that already exists. If it's some local test/dev environment you can try and drop the database and re-create a fresh one...
